services:
  web:
    build: .
    container_name: server_apache
    ports:
      - 8080:80
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./src:/var/www/html
      # - html:/var/www/html
  db:
    image: mariadb
    container_name: server_sql
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
volumes:
  data: null
  html: null